services:
  mysql:
    image: mysql:8.0
    container_name: booking-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass_2024
      MYSQL_DATABASE: booking_portal
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: booking_pass_2024
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./docker/mysql/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
      - ./docker/mysql/03-migration-v2.sql:/docker-entrypoint-initdb.d/03-migration-v2.sql:ro
      - ./docker/mysql/04-seed-v2.sql:/docker-entrypoint-initdb.d/04-seed-v2.sql:ro
      - ./docker/mysql/05-migration-v3.sql:/docker-entrypoint-initdb.d/05-migration-v3.sql:ro
      - ./docker/mysql/06-migration-v4.sql:/docker-entrypoint-initdb.d/06-migration-v4.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass_2024"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-webapp
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booking_portal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: booking_user
      SPRING_DATASOURCE_PASSWORD: booking_pass_2024
      ENCRYPTION_KEY: BookingPortalProdKey2024SecureRotate
    volumes:
      - uploads-data:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  mysql-data:
  uploads-data:
